# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
    ]
