# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20181125_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='student',
            new_name='students',
        ),
    ]
