# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='课程讲师'),
        ),
    ]
