# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='视频访问地址'),
        ),
    ]
